#!/usr/bin/env bash
# Check if an argument is provided
if [ "$#" -ne 1 ]; then
  echo "Usage: $0 {IP_ADDRESS}"
  exit 1
fi

ip_address=$1

# Validate if the argument is a valid IP address
if ! [[ $ip_address =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "Invalid IP address format: $ip_address"
  exit 1
fi

# Ping the IP address 5 times and display the results
ping -c 5 "$ip_address"
