#!/usr/bin/env bash
# Find the process ID (PID) of the running "4-to_infinity_and_beyond.sh" script
process_pid=$(pgrep -f "4-to_infinity_and_beyond.sh")

if [ -n "$process_pid" ]; then
  echo "Stopping process $process_pid"
  # Send the SIGUSR1 signal to the process to terminate it gracefully
  kill -SIGUSR1 "$process_pid"
else
  echo "Process '4-to_infinity_and_beyond.sh' is not running."
fi
