#!/usr/bin/env bash
# Find the process ID (PID) of the running "4-to_infinity_and_beyond.sh" script
process_pid=$(pgrep -f "4-to_infinity_and_beyond.sh")

if [ -n "$process_pid" ]; then
	  echo "Stopping process 4-to_infinity_and_beyond (PID: $process_pid)"
	    # Get the PGID of the process
	      process_pgid=$(ps -o pgid= -p "$process_pid" | tr -d '[:space:]')

	        # Send the SIGTERM signal to the process group to terminate it gracefully
		  kill -- "-$process_pgid"

		    # Wait for the process to terminate
		      wait "$process_pid"
	      else
		        echo "Process '4-to_infinity_and_beyond.sh' is not running."
fi

