#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.

# Check if the script is being run with root privileges
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root."
    exit 1
fi

# Update the DNS resolution for localhost and facebook.com
{
    echo "127.0.0.2 localhost"
    echo "8.8.8.8 facebook.com"
} >> /etc/hosts

echo "DNS configurations updated successfully."

